-- MySQL Script generated by MySQL Workbench
-- Wed 15 Mar 2017 12:02:09 AM +03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema library
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema library
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `library` DEFAULT CHARACTER SET utf8 ;
USE `library` ;

-- -----------------------------------------------------
-- Table `library`.`book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`book` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL,
  `author` VARCHAR(255) NULL,
  `brief` VARCHAR(50) NULL,
  `publish_year` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `library`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`employee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `date_of_birth` DATE NULL,
  `email` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `library`.`book_has_employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`book_has_employee` (
  `book_id` INT NOT NULL,
  `employee_id` INT NOT NULL,
  PRIMARY KEY (`book_id`, `employee_id`),
  INDEX `fk_book_has_employee_employee_idx` (`employee_id` ASC),
  INDEX `fk_book_has_employee_book_idx` (`book_id` ASC),
  CONSTRAINT `fk_book_has_employee_book`
    FOREIGN KEY (`book_id`)
    REFERENCES `library`.`book` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_book_has_employee_employee`
    FOREIGN KEY (`employee_id`)
    REFERENCES `library`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `library`.`book`
-- -----------------------------------------------------
START TRANSACTION;
USE `library`;
INSERT INTO `library`.`book` (`id`, `title`, `author`, `brief`, `publish_year`) VALUES (DEFAULT, 'Приемы объектно-ориентированного проектирования. Паттерны проектирования', 'Джон Влиссидес', 'Паттерны проектирования', '2015');

COMMIT;


-- -----------------------------------------------------
-- Data for table `library`.`employee`
-- -----------------------------------------------------
START TRANSACTION;
USE `library`;
INSERT INTO `library`.`employee` (`id`, `name`, `date_of_birth`, `email`) VALUES (DEFAULT, 'John Doe', '1990-12-01', 'john_doe@gmail.com');

COMMIT;

